/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manga4Read;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author tenshi
 */
public class descargar extends javax.swing.JDialog {

    /**
     * Creates new form descargar1
     */
    static String nombreManga;
    static int numeroPag;
    static int count;
    public descargar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        numeroPag=Integer.parseInt(database.consultarUno("select count (*) from temporal"));
        count=0;
        this.setVisible(rootPaneCheckingEnabled);
    }
    
    Timer timer = new Timer (1000, new ActionListener () 
    { 
        public void actionPerformed(ActionEvent e) 
        { 
            try {
            // TODO code application logic here
                for(int r=0;r<2;r++){
                    Thread archivo1 = new Thread (new ThreadDownload(jTableDecargas.getValueAt(count, 1).toString(),jTableDecargas.getValueAt(count, 2).toString()));
                    count++;
                    archivo1.start();
                    Thread.sleep(10);
                    archivo1.join();   
                    if(count==numeroPag){
                        timer.stop();
                        System.out.println("Terminado");
                        dispose();
                        break;
                    }
                }
        } catch (InterruptedException ex) {
            Logger.getLogger(descargar.class.getName()).log(Level.SEVERE, null, ex);
        }
         } 
    });
    
    public void llenarTabla(){ 
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTableDecargas.setModel(modelo);
            Class.forName("org.sqlite.JDBC");//especificamos el driver
            Connection conn = DriverManager.getConnection("jdbc:sqlite:mangas.db"); //creamos la conexión, si la BD no existe la crea
            java.sql.PreparedStatement stat = conn.prepareStatement("select * from temporal");
            ResultSet rs = stat.executeQuery();
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            modelo.addColumn("Pag.");
            modelo.addColumn("Enlace");
            modelo.addColumn("Estado");
            
            //Creando las filas para el JTable
            while (rs.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            rs.close();
            stat.close();
        } catch (ClassNotFoundException | SQLException ex) {
            //ex.printStackTrace();
        }
        TableColumn columna = jTableDecargas.getColumn("Pag.");
        columna.setPreferredWidth(20);
        columna = jTableDecargas.getColumn("Enlace");
        columna.setPreferredWidth(320);
        columna = jTableDecargas.getColumn("Estado");
        columna.setPreferredWidth(50);
        
    }
    
    public void crearDirectorio(){
        try {
            //Crear Carpeta 
            nombreManga=jTableDecargas.getValueAt(0, 2).toString();
             System.out.println("Directorio: "+nombreManga);
            nombreManga=nombreManga.replaceFirst("Descargas/","");
            nombreManga=nombreManga.replaceFirst("/.*","");
           
            File directorio = new File("Descargas/"+nombreManga);
		   if (directorio.mkdirs())
		     System.out.println("Se ha creado directorio");
                   else{
                       System.out.println("No se ha podido crear el directorio");
                       dispose();
                   }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDecargas = new javax.swing.JTable();
        jButtonCCap = new javax.swing.JButton();
        jButtonCAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableDecargas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDecargas);

        jButtonCCap.setText("Cancelar capitulo");
        jButtonCCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCCapActionPerformed(evt);
            }
        });

        jButtonCAll.setText("Cancelar todo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCCap)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCCap)
                    .addComponent(jButtonCAll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        llenarTabla(); 
        crearDirectorio();
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonCCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCCapActionPerformed
        // TODO add your handling code here:
        timer.stop();
        dispose();
    }//GEN-LAST:event_jButtonCCapActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(descargar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(descargar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(descargar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(descargar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                descargar1 dialog = new descargar1(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCAll;
    private javax.swing.JButton jButtonCCap;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDecargas;
    // End of variables declaration//GEN-END:variables
}
